name             'workstation'
maintainer       'Etki'
maintainer_email 'etki@etki.me'
license          'MIT'
description      'Installs/Configures workstation'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

depends 'docker', '~> 2.13.0'
depends 'git', '~> 5.0.1'
depends 'chrome', '~> 2.0.0'
depends 'chromedriver', '~> 2.0.0'
depends 'phantomjs2', '~> 1.1.0'
depends 'ghostdriver'#, '~> 1.1.0'
depends 'java', '~> 1.43.0'
depends 'vagrant'#, '~> 0.6.0'
depends 'nvm', '~> 0.1.7'
depends 'rvm', '~> 0.9.4'
depends 'selenium'#, '~> 3.7.4'